name: multi-trigger

on:
  push:
    branches:[main]

  workflow_dispatch:

  schedule:
    - cron: '*/2 * * * *'

jobs:
  handle-event:
    runs-on: ubuntu-latest

    steps:
      - name: print trigger type
        run: |
          echo "trigger by ${{ github.event_name }}"

          if [ "${{ github.event_name }}" = "push" ]; then
            echo "code was pushed"

          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual execution"

          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Running on schedule"

          else
            echo "unknown trigger"
          fi